- name: Install MySQL client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: load mysql schema
  ansible.builtin.shell: mysql -h mysql.joindevops.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql